name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # Gợi ý: pin bản bạn muốn (ví dụ 0.151.0 hoặc 0.152.2)
          hugo-version: '0.152.2'
          extended: true
          
      - name: Install Dart Sass (binary, keep folder structure)
        run: |
          set -eux
          SASS_VER=1.77.8
          curl -fsSL -o /tmp/dart-sass.tgz \
            "https://github.com/sass/dart-sass/releases/download/${SASS_VER}/dart-sass-${SASS_VER}-linux-x64.tar.gz"
          # Giải nén thẳng vào $HOME (sẽ có $HOME/dart-sass/...)
          tar -xzf /tmp/dart-sass.tgz -C "$HOME"
          # Dọn các cài cũ có thể che PATH
          rm -f "$HOME/bin/sass" || true
          mkdir -p "$HOME/bin"
          # Tạo symlink tới script 'sass' trong thư mục vừa giải nén
          ln -s "$HOME/dart-sass/sass" "$HOME/bin/sass"
          # Đảm bảo quyền thực thi (thường tar đã giữ)
          chmod +x "$HOME/dart-sass/sass" "$HOME/dart-sass/src/dart"
          # Thêm PATH cho các step KẾ TIẾP
          echo "$HOME/bin" >> "$GITHUB_PATH"

      - name: Verify Dart Sass
        run: |
          export PATH="$HOME/bin:$PATH"    # dùng ngay trong step hiện tại
          command -v sass
          sass --version



      # Quan trọng: đặt id để dùng outputs.base_url
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      # Nếu là Project Pages (repo không phải user.github.io), giữ dấu "/" cuối để tạo URL đúng
      - name: Build
        run: |
          hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
