name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # Gợi ý: pin bản bạn muốn (ví dụ 0.151.0 hoặc 0.152.2)
          hugo-version: '0.152.2'
          extended: true

      - name: Download and Install Dart Sass (Manual, No Sudo)
        run: |
          set -eux
          mkdir -p "$HOME/bin"
          curl -fsSL -o /tmp/dart-sass.tgz \
            https://github.com/sass/dart-sass/releases/download/1.77.8/dart-sass-1.77.8-linux-x64.tar.gz
          tar -xzf /tmp/dart-sass.tgz -C /tmp
          cp /tmp/dart-sass/sass "$HOME/bin/sass"
          chmod +x "$HOME/bin/sass"
          echo "$HOME/bin" >> "$GITHUB_PATH"

      - name: Verify Dart Sass
        run: |
          command -v sass
          sass --version


      # Quan trọng: đặt id để dùng outputs.base_url
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      # Nếu là Project Pages (repo không phải user.github.io), giữ dấu "/" cuối để tạo URL đúng
      - name: Build
        run: |
          hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
